// Code generated by protoc-gen-go. DO NOT EDIT.
// source: service.proto

package employee

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Employee struct {
	Id                   int64    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name                 string   `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Age                  int64    `protobuf:"varint,3,opt,name=age,proto3" json:"age,omitempty"`
	UnitId               int64    `protobuf:"varint,4,opt,name=unit_id,json=unitId,proto3" json:"unit_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Employee) Reset()         { *m = Employee{} }
func (m *Employee) String() string { return proto.CompactTextString(m) }
func (*Employee) ProtoMessage()    {}
func (*Employee) Descriptor() ([]byte, []int) {
	return fileDescriptor_a0b84a42fa06f626, []int{0}
}

func (m *Employee) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Employee.Unmarshal(m, b)
}
func (m *Employee) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Employee.Marshal(b, m, deterministic)
}
func (m *Employee) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Employee.Merge(m, src)
}
func (m *Employee) XXX_Size() int {
	return xxx_messageInfo_Employee.Size(m)
}
func (m *Employee) XXX_DiscardUnknown() {
	xxx_messageInfo_Employee.DiscardUnknown(m)
}

var xxx_messageInfo_Employee proto.InternalMessageInfo

func (m *Employee) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *Employee) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Employee) GetAge() int64 {
	if m != nil {
		return m.Age
	}
	return 0
}

func (m *Employee) GetUnitId() int64 {
	if m != nil {
		return m.UnitId
	}
	return 0
}

type GetEmployeesRequest struct {
	Id                   int64    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetEmployeesRequest) Reset()         { *m = GetEmployeesRequest{} }
func (m *GetEmployeesRequest) String() string { return proto.CompactTextString(m) }
func (*GetEmployeesRequest) ProtoMessage()    {}
func (*GetEmployeesRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_a0b84a42fa06f626, []int{1}
}

func (m *GetEmployeesRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetEmployeesRequest.Unmarshal(m, b)
}
func (m *GetEmployeesRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetEmployeesRequest.Marshal(b, m, deterministic)
}
func (m *GetEmployeesRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetEmployeesRequest.Merge(m, src)
}
func (m *GetEmployeesRequest) XXX_Size() int {
	return xxx_messageInfo_GetEmployeesRequest.Size(m)
}
func (m *GetEmployeesRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetEmployeesRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetEmployeesRequest proto.InternalMessageInfo

func (m *GetEmployeesRequest) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

type GetEmployeesResponse struct {
	Emp                  []*Employee `protobuf:"bytes,1,rep,name=emp,proto3" json:"emp,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *GetEmployeesResponse) Reset()         { *m = GetEmployeesResponse{} }
func (m *GetEmployeesResponse) String() string { return proto.CompactTextString(m) }
func (*GetEmployeesResponse) ProtoMessage()    {}
func (*GetEmployeesResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_a0b84a42fa06f626, []int{2}
}

func (m *GetEmployeesResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetEmployeesResponse.Unmarshal(m, b)
}
func (m *GetEmployeesResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetEmployeesResponse.Marshal(b, m, deterministic)
}
func (m *GetEmployeesResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetEmployeesResponse.Merge(m, src)
}
func (m *GetEmployeesResponse) XXX_Size() int {
	return xxx_messageInfo_GetEmployeesResponse.Size(m)
}
func (m *GetEmployeesResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetEmployeesResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetEmployeesResponse proto.InternalMessageInfo

func (m *GetEmployeesResponse) GetEmp() []*Employee {
	if m != nil {
		return m.Emp
	}
	return nil
}

type GetOneEmployeeRequest struct {
	Id                   int64    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Id1                  int64    `protobuf:"varint,2,opt,name=id1,proto3" json:"id1,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetOneEmployeeRequest) Reset()         { *m = GetOneEmployeeRequest{} }
func (m *GetOneEmployeeRequest) String() string { return proto.CompactTextString(m) }
func (*GetOneEmployeeRequest) ProtoMessage()    {}
func (*GetOneEmployeeRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_a0b84a42fa06f626, []int{3}
}

func (m *GetOneEmployeeRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetOneEmployeeRequest.Unmarshal(m, b)
}
func (m *GetOneEmployeeRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetOneEmployeeRequest.Marshal(b, m, deterministic)
}
func (m *GetOneEmployeeRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetOneEmployeeRequest.Merge(m, src)
}
func (m *GetOneEmployeeRequest) XXX_Size() int {
	return xxx_messageInfo_GetOneEmployeeRequest.Size(m)
}
func (m *GetOneEmployeeRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetOneEmployeeRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetOneEmployeeRequest proto.InternalMessageInfo

func (m *GetOneEmployeeRequest) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *GetOneEmployeeRequest) GetId1() int64 {
	if m != nil {
		return m.Id1
	}
	return 0
}

type GetOneEmployeeResponse struct {
	Emp                  *Employee `protobuf:"bytes,1,opt,name=emp,proto3" json:"emp,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *GetOneEmployeeResponse) Reset()         { *m = GetOneEmployeeResponse{} }
func (m *GetOneEmployeeResponse) String() string { return proto.CompactTextString(m) }
func (*GetOneEmployeeResponse) ProtoMessage()    {}
func (*GetOneEmployeeResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_a0b84a42fa06f626, []int{4}
}

func (m *GetOneEmployeeResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetOneEmployeeResponse.Unmarshal(m, b)
}
func (m *GetOneEmployeeResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetOneEmployeeResponse.Marshal(b, m, deterministic)
}
func (m *GetOneEmployeeResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetOneEmployeeResponse.Merge(m, src)
}
func (m *GetOneEmployeeResponse) XXX_Size() int {
	return xxx_messageInfo_GetOneEmployeeResponse.Size(m)
}
func (m *GetOneEmployeeResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetOneEmployeeResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetOneEmployeeResponse proto.InternalMessageInfo

func (m *GetOneEmployeeResponse) GetEmp() *Employee {
	if m != nil {
		return m.Emp
	}
	return nil
}

type CreateEmployeeRequest struct {
	Id                   int64     `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Emp                  *Employee `protobuf:"bytes,2,opt,name=emp,proto3" json:"emp,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *CreateEmployeeRequest) Reset()         { *m = CreateEmployeeRequest{} }
func (m *CreateEmployeeRequest) String() string { return proto.CompactTextString(m) }
func (*CreateEmployeeRequest) ProtoMessage()    {}
func (*CreateEmployeeRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_a0b84a42fa06f626, []int{5}
}

func (m *CreateEmployeeRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateEmployeeRequest.Unmarshal(m, b)
}
func (m *CreateEmployeeRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateEmployeeRequest.Marshal(b, m, deterministic)
}
func (m *CreateEmployeeRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateEmployeeRequest.Merge(m, src)
}
func (m *CreateEmployeeRequest) XXX_Size() int {
	return xxx_messageInfo_CreateEmployeeRequest.Size(m)
}
func (m *CreateEmployeeRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateEmployeeRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CreateEmployeeRequest proto.InternalMessageInfo

func (m *CreateEmployeeRequest) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *CreateEmployeeRequest) GetEmp() *Employee {
	if m != nil {
		return m.Emp
	}
	return nil
}

type CreateEmployeeResponse struct {
	Emp                  *Employee `protobuf:"bytes,1,opt,name=emp,proto3" json:"emp,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *CreateEmployeeResponse) Reset()         { *m = CreateEmployeeResponse{} }
func (m *CreateEmployeeResponse) String() string { return proto.CompactTextString(m) }
func (*CreateEmployeeResponse) ProtoMessage()    {}
func (*CreateEmployeeResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_a0b84a42fa06f626, []int{6}
}

func (m *CreateEmployeeResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateEmployeeResponse.Unmarshal(m, b)
}
func (m *CreateEmployeeResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateEmployeeResponse.Marshal(b, m, deterministic)
}
func (m *CreateEmployeeResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateEmployeeResponse.Merge(m, src)
}
func (m *CreateEmployeeResponse) XXX_Size() int {
	return xxx_messageInfo_CreateEmployeeResponse.Size(m)
}
func (m *CreateEmployeeResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateEmployeeResponse.DiscardUnknown(m)
}

var xxx_messageInfo_CreateEmployeeResponse proto.InternalMessageInfo

func (m *CreateEmployeeResponse) GetEmp() *Employee {
	if m != nil {
		return m.Emp
	}
	return nil
}

type UpdateEmployeeRequest struct {
	Id                   int64     `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Id1                  int64     `protobuf:"varint,2,opt,name=id1,proto3" json:"id1,omitempty"`
	Emp                  *Employee `protobuf:"bytes,3,opt,name=emp,proto3" json:"emp,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *UpdateEmployeeRequest) Reset()         { *m = UpdateEmployeeRequest{} }
func (m *UpdateEmployeeRequest) String() string { return proto.CompactTextString(m) }
func (*UpdateEmployeeRequest) ProtoMessage()    {}
func (*UpdateEmployeeRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_a0b84a42fa06f626, []int{7}
}

func (m *UpdateEmployeeRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateEmployeeRequest.Unmarshal(m, b)
}
func (m *UpdateEmployeeRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateEmployeeRequest.Marshal(b, m, deterministic)
}
func (m *UpdateEmployeeRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateEmployeeRequest.Merge(m, src)
}
func (m *UpdateEmployeeRequest) XXX_Size() int {
	return xxx_messageInfo_UpdateEmployeeRequest.Size(m)
}
func (m *UpdateEmployeeRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateEmployeeRequest.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateEmployeeRequest proto.InternalMessageInfo

func (m *UpdateEmployeeRequest) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *UpdateEmployeeRequest) GetId1() int64 {
	if m != nil {
		return m.Id1
	}
	return 0
}

func (m *UpdateEmployeeRequest) GetEmp() *Employee {
	if m != nil {
		return m.Emp
	}
	return nil
}

type UpdateEmployeeResponse struct {
	Emp                  *Employee `protobuf:"bytes,1,opt,name=emp,proto3" json:"emp,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *UpdateEmployeeResponse) Reset()         { *m = UpdateEmployeeResponse{} }
func (m *UpdateEmployeeResponse) String() string { return proto.CompactTextString(m) }
func (*UpdateEmployeeResponse) ProtoMessage()    {}
func (*UpdateEmployeeResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_a0b84a42fa06f626, []int{8}
}

func (m *UpdateEmployeeResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateEmployeeResponse.Unmarshal(m, b)
}
func (m *UpdateEmployeeResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateEmployeeResponse.Marshal(b, m, deterministic)
}
func (m *UpdateEmployeeResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateEmployeeResponse.Merge(m, src)
}
func (m *UpdateEmployeeResponse) XXX_Size() int {
	return xxx_messageInfo_UpdateEmployeeResponse.Size(m)
}
func (m *UpdateEmployeeResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateEmployeeResponse.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateEmployeeResponse proto.InternalMessageInfo

func (m *UpdateEmployeeResponse) GetEmp() *Employee {
	if m != nil {
		return m.Emp
	}
	return nil
}

type DeleteEmployeeRequest struct {
	Id                   int64    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Id1                  int64    `protobuf:"varint,2,opt,name=id1,proto3" json:"id1,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeleteEmployeeRequest) Reset()         { *m = DeleteEmployeeRequest{} }
func (m *DeleteEmployeeRequest) String() string { return proto.CompactTextString(m) }
func (*DeleteEmployeeRequest) ProtoMessage()    {}
func (*DeleteEmployeeRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_a0b84a42fa06f626, []int{9}
}

func (m *DeleteEmployeeRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteEmployeeRequest.Unmarshal(m, b)
}
func (m *DeleteEmployeeRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteEmployeeRequest.Marshal(b, m, deterministic)
}
func (m *DeleteEmployeeRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteEmployeeRequest.Merge(m, src)
}
func (m *DeleteEmployeeRequest) XXX_Size() int {
	return xxx_messageInfo_DeleteEmployeeRequest.Size(m)
}
func (m *DeleteEmployeeRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteEmployeeRequest.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteEmployeeRequest proto.InternalMessageInfo

func (m *DeleteEmployeeRequest) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *DeleteEmployeeRequest) GetId1() int64 {
	if m != nil {
		return m.Id1
	}
	return 0
}

type DeleteEmployeeResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeleteEmployeeResponse) Reset()         { *m = DeleteEmployeeResponse{} }
func (m *DeleteEmployeeResponse) String() string { return proto.CompactTextString(m) }
func (*DeleteEmployeeResponse) ProtoMessage()    {}
func (*DeleteEmployeeResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_a0b84a42fa06f626, []int{10}
}

func (m *DeleteEmployeeResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteEmployeeResponse.Unmarshal(m, b)
}
func (m *DeleteEmployeeResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteEmployeeResponse.Marshal(b, m, deterministic)
}
func (m *DeleteEmployeeResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteEmployeeResponse.Merge(m, src)
}
func (m *DeleteEmployeeResponse) XXX_Size() int {
	return xxx_messageInfo_DeleteEmployeeResponse.Size(m)
}
func (m *DeleteEmployeeResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteEmployeeResponse.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteEmployeeResponse proto.InternalMessageInfo

func init() {
	proto.RegisterType((*Employee)(nil), "employee.Employee")
	proto.RegisterType((*GetEmployeesRequest)(nil), "employee.GetEmployeesRequest")
	proto.RegisterType((*GetEmployeesResponse)(nil), "employee.GetEmployeesResponse")
	proto.RegisterType((*GetOneEmployeeRequest)(nil), "employee.GetOneEmployeeRequest")
	proto.RegisterType((*GetOneEmployeeResponse)(nil), "employee.GetOneEmployeeResponse")
	proto.RegisterType((*CreateEmployeeRequest)(nil), "employee.CreateEmployeeRequest")
	proto.RegisterType((*CreateEmployeeResponse)(nil), "employee.CreateEmployeeResponse")
	proto.RegisterType((*UpdateEmployeeRequest)(nil), "employee.UpdateEmployeeRequest")
	proto.RegisterType((*UpdateEmployeeResponse)(nil), "employee.UpdateEmployeeResponse")
	proto.RegisterType((*DeleteEmployeeRequest)(nil), "employee.DeleteEmployeeRequest")
	proto.RegisterType((*DeleteEmployeeResponse)(nil), "employee.DeleteEmployeeResponse")
}

func init() { proto.RegisterFile("service.proto", fileDescriptor_a0b84a42fa06f626) }

var fileDescriptor_a0b84a42fa06f626 = []byte{
	// 458 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x9c, 0x94, 0xdd, 0x6a, 0xd4, 0x40,
	0x14, 0xc7, 0xc9, 0x07, 0xb1, 0x1e, 0xf1, 0x83, 0xd3, 0xee, 0x1a, 0x63, 0xd5, 0x38, 0xa8, 0x2c,
	0x5e, 0x6c, 0x68, 0xbd, 0xaa, 0x48, 0x6f, 0x54, 0x8a, 0xa0, 0x08, 0x11, 0x2f, 0xbc, 0x2a, 0xb1,
	0x39, 0x2c, 0x03, 0xbb, 0x33, 0x71, 0x67, 0x2a, 0x88, 0xf4, 0xc6, 0x57, 0xf0, 0x65, 0x7c, 0x0f,
	0x5f, 0xc1, 0x07, 0x91, 0x99, 0xd9, 0x68, 0x9a, 0x4e, 0x5a, 0xd7, 0xbb, 0xf9, 0x38, 0xf3, 0xff,
	0xfd, 0x67, 0xce, 0x3f, 0x81, 0xab, 0x8a, 0x96, 0x9f, 0xf9, 0x11, 0x4d, 0x9b, 0xa5, 0xd4, 0x12,
	0x37, 0x68, 0xd1, 0xcc, 0xe5, 0x17, 0xa2, 0x6c, 0x7b, 0x26, 0xe5, 0x6c, 0x4e, 0x45, 0xd5, 0xf0,
	0xa2, 0x12, 0x42, 0xea, 0x4a, 0x73, 0x29, 0x94, 0xab, 0x63, 0x1f, 0x60, 0xe3, 0xe5, 0xaa, 0x12,
	0xaf, 0x41, 0xc8, 0xeb, 0x34, 0xc8, 0x83, 0x49, 0x54, 0x86, 0xbc, 0x46, 0x84, 0x58, 0x54, 0x0b,
	0x4a, 0xc3, 0x3c, 0x98, 0x5c, 0x2e, 0xed, 0x18, 0x6f, 0x40, 0x54, 0xcd, 0x28, 0x8d, 0x6c, 0x91,
	0x19, 0xe2, 0x4d, 0xb8, 0x74, 0x2c, 0xb8, 0x3e, 0xe4, 0x75, 0x1a, 0xdb, 0xd5, 0xc4, 0x4c, 0x5f,
	0xd5, 0xec, 0x21, 0x6c, 0x1e, 0x90, 0x6e, 0xd5, 0x55, 0x49, 0x9f, 0x8e, 0x49, 0xe9, 0x3e, 0x85,
	0x3d, 0x83, 0xad, 0xd3, 0x65, 0xaa, 0x91, 0x42, 0x11, 0x3e, 0x80, 0x88, 0x16, 0x4d, 0x1a, 0xe4,
	0xd1, 0xe4, 0xca, 0x2e, 0x4e, 0xdb, 0xfb, 0x4c, 0xdb, 0xca, 0xd2, 0x6c, 0xb3, 0x3d, 0x18, 0x1d,
	0x90, 0x7e, 0x2b, 0xe8, 0xcf, 0xb2, 0x1f, 0x63, 0x8c, 0xf3, 0x7a, 0xc7, 0xde, 0x25, 0x2a, 0xcd,
	0x90, 0xed, 0xc3, 0xb8, 0x7f, 0xb4, 0x8f, 0x0e, 0xce, 0x43, 0xbf, 0x81, 0xd1, 0xf3, 0x25, 0x55,
	0xfa, 0x42, 0xf4, 0x4a, 0x2e, 0x3c, 0x5f, 0x6e, 0x1f, 0xc6, 0x7d, 0xb9, 0xb5, 0xec, 0x1c, 0xc2,
	0xe8, 0x7d, 0x53, 0xff, 0x83, 0x9d, 0x33, 0x2f, 0xd1, 0x02, 0xa2, 0x0b, 0x0d, 0xf6, 0x01, 0x6b,
	0x19, 0xdc, 0x83, 0xd1, 0x0b, 0x9a, 0xd3, 0x7f, 0x18, 0x64, 0x29, 0x8c, 0xfb, 0x47, 0x1d, 0x7a,
	0xf7, 0x47, 0x0c, 0xd7, 0xdb, 0xc5, 0x77, 0xee, 0x0b, 0xc0, 0x23, 0x88, 0x5f, 0x73, 0xa5, 0xf1,
	0xce, 0x5f, 0x27, 0x9e, 0x20, 0x66, 0x77, 0x87, 0xb6, 0x9d, 0x34, 0xdb, 0xfe, 0xf6, 0xf3, 0xd7,
	0xf7, 0x70, 0x8c, 0x5b, 0x85, 0x09, 0x74, 0xf1, 0x95, 0xd7, 0x27, 0x45, 0x7b, 0x42, 0xe1, 0x1c,
	0xe2, 0x92, 0xaa, 0x1a, 0xef, 0x9d, 0x52, 0x39, 0x1b, 0xc4, 0x2c, 0x1f, 0x2e, 0x58, 0x81, 0xee,
	0x5b, 0xd0, 0x6d, 0xbc, 0xe5, 0x01, 0x99, 0xd9, 0xce, 0x09, 0x2e, 0x20, 0x71, 0xe1, 0xe8, 0xf2,
	0xbc, 0xe9, 0xeb, 0xf2, 0xfc, 0x79, 0x62, 0xb9, 0xe5, 0x65, 0x6c, 0xd3, 0xc3, 0x7b, 0x6a, 0x5a,
	0x85, 0x0a, 0x12, 0xd7, 0xea, 0x2e, 0xce, 0x9b, 0xae, 0x2e, 0xce, 0x9f, 0x0e, 0xf6, 0xc8, 0xe2,
	0xf2, 0x6c, 0xf8, 0x7a, 0x0e, 0x2a, 0x20, 0x71, 0x4d, 0xee, 0x42, 0xbd, 0x89, 0xe9, 0x42, 0xfd,
	0xb9, 0x68, 0xdf, 0xf4, 0xf1, 0x30, 0xf4, 0x63, 0x62, 0xff, 0x80, 0x4f, 0x7e, 0x07, 0x00, 0x00,
	0xff, 0xff, 0xde, 0xb7, 0xb3, 0x15, 0x3a, 0x05, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// EmployeeServiceClient is the client API for EmployeeService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type EmployeeServiceClient interface {
	List(ctx context.Context, in *GetEmployeesRequest, opts ...grpc.CallOption) (*GetEmployeesResponse, error)
	Read(ctx context.Context, in *GetOneEmployeeRequest, opts ...grpc.CallOption) (*GetOneEmployeeResponse, error)
	Create(ctx context.Context, in *CreateEmployeeRequest, opts ...grpc.CallOption) (*CreateEmployeeResponse, error)
	Update(ctx context.Context, in *UpdateEmployeeRequest, opts ...grpc.CallOption) (*UpdateEmployeeResponse, error)
	Delete(ctx context.Context, in *DeleteEmployeeRequest, opts ...grpc.CallOption) (*DeleteEmployeeResponse, error)
}

type employeeServiceClient struct {
	cc *grpc.ClientConn
}

func NewEmployeeServiceClient(cc *grpc.ClientConn) EmployeeServiceClient {
	return &employeeServiceClient{cc}
}

func (c *employeeServiceClient) List(ctx context.Context, in *GetEmployeesRequest, opts ...grpc.CallOption) (*GetEmployeesResponse, error) {
	out := new(GetEmployeesResponse)
	err := c.cc.Invoke(ctx, "/employee.EmployeeService/List", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *employeeServiceClient) Read(ctx context.Context, in *GetOneEmployeeRequest, opts ...grpc.CallOption) (*GetOneEmployeeResponse, error) {
	out := new(GetOneEmployeeResponse)
	err := c.cc.Invoke(ctx, "/employee.EmployeeService/Read", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *employeeServiceClient) Create(ctx context.Context, in *CreateEmployeeRequest, opts ...grpc.CallOption) (*CreateEmployeeResponse, error) {
	out := new(CreateEmployeeResponse)
	err := c.cc.Invoke(ctx, "/employee.EmployeeService/Create", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *employeeServiceClient) Update(ctx context.Context, in *UpdateEmployeeRequest, opts ...grpc.CallOption) (*UpdateEmployeeResponse, error) {
	out := new(UpdateEmployeeResponse)
	err := c.cc.Invoke(ctx, "/employee.EmployeeService/Update", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *employeeServiceClient) Delete(ctx context.Context, in *DeleteEmployeeRequest, opts ...grpc.CallOption) (*DeleteEmployeeResponse, error) {
	out := new(DeleteEmployeeResponse)
	err := c.cc.Invoke(ctx, "/employee.EmployeeService/Delete", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// EmployeeServiceServer is the server API for EmployeeService service.
type EmployeeServiceServer interface {
	List(context.Context, *GetEmployeesRequest) (*GetEmployeesResponse, error)
	Read(context.Context, *GetOneEmployeeRequest) (*GetOneEmployeeResponse, error)
	Create(context.Context, *CreateEmployeeRequest) (*CreateEmployeeResponse, error)
	Update(context.Context, *UpdateEmployeeRequest) (*UpdateEmployeeResponse, error)
	Delete(context.Context, *DeleteEmployeeRequest) (*DeleteEmployeeResponse, error)
}

// UnimplementedEmployeeServiceServer can be embedded to have forward compatible implementations.
type UnimplementedEmployeeServiceServer struct {
}

func (*UnimplementedEmployeeServiceServer) List(ctx context.Context, req *GetEmployeesRequest) (*GetEmployeesResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method List not implemented")
}
func (*UnimplementedEmployeeServiceServer) Read(ctx context.Context, req *GetOneEmployeeRequest) (*GetOneEmployeeResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Read not implemented")
}
func (*UnimplementedEmployeeServiceServer) Create(ctx context.Context, req *CreateEmployeeRequest) (*CreateEmployeeResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Create not implemented")
}
func (*UnimplementedEmployeeServiceServer) Update(ctx context.Context, req *UpdateEmployeeRequest) (*UpdateEmployeeResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Update not implemented")
}
func (*UnimplementedEmployeeServiceServer) Delete(ctx context.Context, req *DeleteEmployeeRequest) (*DeleteEmployeeResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Delete not implemented")
}

func RegisterEmployeeServiceServer(s *grpc.Server, srv EmployeeServiceServer) {
	s.RegisterService(&_EmployeeService_serviceDesc, srv)
}

func _EmployeeService_List_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetEmployeesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EmployeeServiceServer).List(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/employee.EmployeeService/List",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EmployeeServiceServer).List(ctx, req.(*GetEmployeesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _EmployeeService_Read_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetOneEmployeeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EmployeeServiceServer).Read(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/employee.EmployeeService/Read",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EmployeeServiceServer).Read(ctx, req.(*GetOneEmployeeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _EmployeeService_Create_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateEmployeeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EmployeeServiceServer).Create(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/employee.EmployeeService/Create",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EmployeeServiceServer).Create(ctx, req.(*CreateEmployeeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _EmployeeService_Update_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateEmployeeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EmployeeServiceServer).Update(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/employee.EmployeeService/Update",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EmployeeServiceServer).Update(ctx, req.(*UpdateEmployeeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _EmployeeService_Delete_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteEmployeeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EmployeeServiceServer).Delete(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/employee.EmployeeService/Delete",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EmployeeServiceServer).Delete(ctx, req.(*DeleteEmployeeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _EmployeeService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "employee.EmployeeService",
	HandlerType: (*EmployeeServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "List",
			Handler:    _EmployeeService_List_Handler,
		},
		{
			MethodName: "Read",
			Handler:    _EmployeeService_Read_Handler,
		},
		{
			MethodName: "Create",
			Handler:    _EmployeeService_Create_Handler,
		},
		{
			MethodName: "Update",
			Handler:    _EmployeeService_Update_Handler,
		},
		{
			MethodName: "Delete",
			Handler:    _EmployeeService_Delete_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "service.proto",
}
