// Code generated by protoc-gen-go. DO NOT EDIT.
// source: service.proto

package unit

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Unit struct {
	Id                   int64    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name                 string   `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Unit) Reset()         { *m = Unit{} }
func (m *Unit) String() string { return proto.CompactTextString(m) }
func (*Unit) ProtoMessage()    {}
func (*Unit) Descriptor() ([]byte, []int) {
	return fileDescriptor_a0b84a42fa06f626, []int{0}
}

func (m *Unit) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Unit.Unmarshal(m, b)
}
func (m *Unit) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Unit.Marshal(b, m, deterministic)
}
func (m *Unit) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Unit.Merge(m, src)
}
func (m *Unit) XXX_Size() int {
	return xxx_messageInfo_Unit.Size(m)
}
func (m *Unit) XXX_DiscardUnknown() {
	xxx_messageInfo_Unit.DiscardUnknown(m)
}

var xxx_messageInfo_Unit proto.InternalMessageInfo

func (m *Unit) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *Unit) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

type GetUnitsRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetUnitsRequest) Reset()         { *m = GetUnitsRequest{} }
func (m *GetUnitsRequest) String() string { return proto.CompactTextString(m) }
func (*GetUnitsRequest) ProtoMessage()    {}
func (*GetUnitsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_a0b84a42fa06f626, []int{1}
}

func (m *GetUnitsRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetUnitsRequest.Unmarshal(m, b)
}
func (m *GetUnitsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetUnitsRequest.Marshal(b, m, deterministic)
}
func (m *GetUnitsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetUnitsRequest.Merge(m, src)
}
func (m *GetUnitsRequest) XXX_Size() int {
	return xxx_messageInfo_GetUnitsRequest.Size(m)
}
func (m *GetUnitsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetUnitsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetUnitsRequest proto.InternalMessageInfo

type GetUnitsResponse struct {
	Units                []*Unit  `protobuf:"bytes,1,rep,name=units,proto3" json:"units,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetUnitsResponse) Reset()         { *m = GetUnitsResponse{} }
func (m *GetUnitsResponse) String() string { return proto.CompactTextString(m) }
func (*GetUnitsResponse) ProtoMessage()    {}
func (*GetUnitsResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_a0b84a42fa06f626, []int{2}
}

func (m *GetUnitsResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetUnitsResponse.Unmarshal(m, b)
}
func (m *GetUnitsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetUnitsResponse.Marshal(b, m, deterministic)
}
func (m *GetUnitsResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetUnitsResponse.Merge(m, src)
}
func (m *GetUnitsResponse) XXX_Size() int {
	return xxx_messageInfo_GetUnitsResponse.Size(m)
}
func (m *GetUnitsResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetUnitsResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetUnitsResponse proto.InternalMessageInfo

func (m *GetUnitsResponse) GetUnits() []*Unit {
	if m != nil {
		return m.Units
	}
	return nil
}

type GetOneUnitRequest struct {
	Id                   int64    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetOneUnitRequest) Reset()         { *m = GetOneUnitRequest{} }
func (m *GetOneUnitRequest) String() string { return proto.CompactTextString(m) }
func (*GetOneUnitRequest) ProtoMessage()    {}
func (*GetOneUnitRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_a0b84a42fa06f626, []int{3}
}

func (m *GetOneUnitRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetOneUnitRequest.Unmarshal(m, b)
}
func (m *GetOneUnitRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetOneUnitRequest.Marshal(b, m, deterministic)
}
func (m *GetOneUnitRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetOneUnitRequest.Merge(m, src)
}
func (m *GetOneUnitRequest) XXX_Size() int {
	return xxx_messageInfo_GetOneUnitRequest.Size(m)
}
func (m *GetOneUnitRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetOneUnitRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetOneUnitRequest proto.InternalMessageInfo

func (m *GetOneUnitRequest) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

type GetOneUnitResponse struct {
	Unit                 *Unit    `protobuf:"bytes,1,opt,name=unit,proto3" json:"unit,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetOneUnitResponse) Reset()         { *m = GetOneUnitResponse{} }
func (m *GetOneUnitResponse) String() string { return proto.CompactTextString(m) }
func (*GetOneUnitResponse) ProtoMessage()    {}
func (*GetOneUnitResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_a0b84a42fa06f626, []int{4}
}

func (m *GetOneUnitResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetOneUnitResponse.Unmarshal(m, b)
}
func (m *GetOneUnitResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetOneUnitResponse.Marshal(b, m, deterministic)
}
func (m *GetOneUnitResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetOneUnitResponse.Merge(m, src)
}
func (m *GetOneUnitResponse) XXX_Size() int {
	return xxx_messageInfo_GetOneUnitResponse.Size(m)
}
func (m *GetOneUnitResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetOneUnitResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetOneUnitResponse proto.InternalMessageInfo

func (m *GetOneUnitResponse) GetUnit() *Unit {
	if m != nil {
		return m.Unit
	}
	return nil
}

type CreateUnitRequest struct {
	Unit                 *Unit    `protobuf:"bytes,1,opt,name=unit,proto3" json:"unit,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateUnitRequest) Reset()         { *m = CreateUnitRequest{} }
func (m *CreateUnitRequest) String() string { return proto.CompactTextString(m) }
func (*CreateUnitRequest) ProtoMessage()    {}
func (*CreateUnitRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_a0b84a42fa06f626, []int{5}
}

func (m *CreateUnitRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateUnitRequest.Unmarshal(m, b)
}
func (m *CreateUnitRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateUnitRequest.Marshal(b, m, deterministic)
}
func (m *CreateUnitRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateUnitRequest.Merge(m, src)
}
func (m *CreateUnitRequest) XXX_Size() int {
	return xxx_messageInfo_CreateUnitRequest.Size(m)
}
func (m *CreateUnitRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateUnitRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CreateUnitRequest proto.InternalMessageInfo

func (m *CreateUnitRequest) GetUnit() *Unit {
	if m != nil {
		return m.Unit
	}
	return nil
}

type CreateUnitResponse struct {
	Unit                 *Unit    `protobuf:"bytes,1,opt,name=unit,proto3" json:"unit,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateUnitResponse) Reset()         { *m = CreateUnitResponse{} }
func (m *CreateUnitResponse) String() string { return proto.CompactTextString(m) }
func (*CreateUnitResponse) ProtoMessage()    {}
func (*CreateUnitResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_a0b84a42fa06f626, []int{6}
}

func (m *CreateUnitResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateUnitResponse.Unmarshal(m, b)
}
func (m *CreateUnitResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateUnitResponse.Marshal(b, m, deterministic)
}
func (m *CreateUnitResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateUnitResponse.Merge(m, src)
}
func (m *CreateUnitResponse) XXX_Size() int {
	return xxx_messageInfo_CreateUnitResponse.Size(m)
}
func (m *CreateUnitResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateUnitResponse.DiscardUnknown(m)
}

var xxx_messageInfo_CreateUnitResponse proto.InternalMessageInfo

func (m *CreateUnitResponse) GetUnit() *Unit {
	if m != nil {
		return m.Unit
	}
	return nil
}

type UpdateUnitRequest struct {
	Id                   int64    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Unit                 *Unit    `protobuf:"bytes,2,opt,name=unit,proto3" json:"unit,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UpdateUnitRequest) Reset()         { *m = UpdateUnitRequest{} }
func (m *UpdateUnitRequest) String() string { return proto.CompactTextString(m) }
func (*UpdateUnitRequest) ProtoMessage()    {}
func (*UpdateUnitRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_a0b84a42fa06f626, []int{7}
}

func (m *UpdateUnitRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateUnitRequest.Unmarshal(m, b)
}
func (m *UpdateUnitRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateUnitRequest.Marshal(b, m, deterministic)
}
func (m *UpdateUnitRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateUnitRequest.Merge(m, src)
}
func (m *UpdateUnitRequest) XXX_Size() int {
	return xxx_messageInfo_UpdateUnitRequest.Size(m)
}
func (m *UpdateUnitRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateUnitRequest.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateUnitRequest proto.InternalMessageInfo

func (m *UpdateUnitRequest) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *UpdateUnitRequest) GetUnit() *Unit {
	if m != nil {
		return m.Unit
	}
	return nil
}

type UpdateUnitResponse struct {
	Unit                 *Unit    `protobuf:"bytes,1,opt,name=unit,proto3" json:"unit,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UpdateUnitResponse) Reset()         { *m = UpdateUnitResponse{} }
func (m *UpdateUnitResponse) String() string { return proto.CompactTextString(m) }
func (*UpdateUnitResponse) ProtoMessage()    {}
func (*UpdateUnitResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_a0b84a42fa06f626, []int{8}
}

func (m *UpdateUnitResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateUnitResponse.Unmarshal(m, b)
}
func (m *UpdateUnitResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateUnitResponse.Marshal(b, m, deterministic)
}
func (m *UpdateUnitResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateUnitResponse.Merge(m, src)
}
func (m *UpdateUnitResponse) XXX_Size() int {
	return xxx_messageInfo_UpdateUnitResponse.Size(m)
}
func (m *UpdateUnitResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateUnitResponse.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateUnitResponse proto.InternalMessageInfo

func (m *UpdateUnitResponse) GetUnit() *Unit {
	if m != nil {
		return m.Unit
	}
	return nil
}

type DeleteUnitRequest struct {
	Id                   int64    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeleteUnitRequest) Reset()         { *m = DeleteUnitRequest{} }
func (m *DeleteUnitRequest) String() string { return proto.CompactTextString(m) }
func (*DeleteUnitRequest) ProtoMessage()    {}
func (*DeleteUnitRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_a0b84a42fa06f626, []int{9}
}

func (m *DeleteUnitRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteUnitRequest.Unmarshal(m, b)
}
func (m *DeleteUnitRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteUnitRequest.Marshal(b, m, deterministic)
}
func (m *DeleteUnitRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteUnitRequest.Merge(m, src)
}
func (m *DeleteUnitRequest) XXX_Size() int {
	return xxx_messageInfo_DeleteUnitRequest.Size(m)
}
func (m *DeleteUnitRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteUnitRequest.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteUnitRequest proto.InternalMessageInfo

func (m *DeleteUnitRequest) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

type DeleteUnitResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeleteUnitResponse) Reset()         { *m = DeleteUnitResponse{} }
func (m *DeleteUnitResponse) String() string { return proto.CompactTextString(m) }
func (*DeleteUnitResponse) ProtoMessage()    {}
func (*DeleteUnitResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_a0b84a42fa06f626, []int{10}
}

func (m *DeleteUnitResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteUnitResponse.Unmarshal(m, b)
}
func (m *DeleteUnitResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteUnitResponse.Marshal(b, m, deterministic)
}
func (m *DeleteUnitResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteUnitResponse.Merge(m, src)
}
func (m *DeleteUnitResponse) XXX_Size() int {
	return xxx_messageInfo_DeleteUnitResponse.Size(m)
}
func (m *DeleteUnitResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteUnitResponse.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteUnitResponse proto.InternalMessageInfo

func init() {
	proto.RegisterType((*Unit)(nil), "unit.Unit")
	proto.RegisterType((*GetUnitsRequest)(nil), "unit.GetUnitsRequest")
	proto.RegisterType((*GetUnitsResponse)(nil), "unit.GetUnitsResponse")
	proto.RegisterType((*GetOneUnitRequest)(nil), "unit.GetOneUnitRequest")
	proto.RegisterType((*GetOneUnitResponse)(nil), "unit.GetOneUnitResponse")
	proto.RegisterType((*CreateUnitRequest)(nil), "unit.CreateUnitRequest")
	proto.RegisterType((*CreateUnitResponse)(nil), "unit.CreateUnitResponse")
	proto.RegisterType((*UpdateUnitRequest)(nil), "unit.UpdateUnitRequest")
	proto.RegisterType((*UpdateUnitResponse)(nil), "unit.UpdateUnitResponse")
	proto.RegisterType((*DeleteUnitRequest)(nil), "unit.DeleteUnitRequest")
	proto.RegisterType((*DeleteUnitResponse)(nil), "unit.DeleteUnitResponse")
}

func init() { proto.RegisterFile("service.proto", fileDescriptor_a0b84a42fa06f626) }

var fileDescriptor_a0b84a42fa06f626 = []byte{
	// 396 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x8c, 0x93, 0x4f, 0x4e, 0xe3, 0x30,
	0x18, 0xc5, 0x95, 0x34, 0x8d, 0x66, 0xbe, 0x4e, 0x3b, 0x93, 0x6f, 0xf8, 0x13, 0x45, 0x08, 0x45,
	0xee, 0xa6, 0xea, 0xa2, 0x91, 0xda, 0xae, 0xd8, 0x16, 0xd4, 0x0d, 0xa8, 0x28, 0xa8, 0x07, 0x08,
	0xc4, 0xaa, 0x2c, 0x15, 0x27, 0xd4, 0x2e, 0x1b, 0xc4, 0x86, 0x2b, 0xb0, 0xe6, 0x54, 0x5c, 0x81,
	0x83, 0xa0, 0xd8, 0x35, 0xa4, 0x89, 0x80, 0xee, 0x92, 0xe7, 0xe7, 0xdf, 0xb3, 0xbf, 0x97, 0x40,
	0x5b, 0xd0, 0xd5, 0x3d, 0xbb, 0xa1, 0x83, 0x7c, 0x95, 0xc9, 0x0c, 0x9d, 0x35, 0x67, 0x32, 0x38,
	0x5a, 0x64, 0xd9, 0x62, 0x49, 0xa3, 0x24, 0x67, 0x51, 0xc2, 0x79, 0x26, 0x13, 0xc9, 0x32, 0x2e,
	0xb4, 0x87, 0xf4, 0xc1, 0x99, 0x73, 0x26, 0xb1, 0x03, 0x36, 0x4b, 0x7d, 0x2b, 0xb4, 0x7a, 0x8d,
	0xd8, 0x66, 0x29, 0x22, 0x38, 0x3c, 0xb9, 0xa5, 0xbe, 0x1d, 0x5a, 0xbd, 0xdf, 0xb1, 0x7a, 0x26,
	0x1e, 0xfc, 0x9d, 0x52, 0x59, 0xd8, 0x45, 0x4c, 0xef, 0xd6, 0x54, 0x48, 0x32, 0x86, 0x7f, 0x9f,
	0x92, 0xc8, 0x33, 0x2e, 0x28, 0x86, 0xd0, 0x2c, 0x82, 0x85, 0x6f, 0x85, 0x8d, 0x5e, 0x6b, 0x08,
	0x83, 0xe2, 0x6d, 0x50, 0x78, 0x62, 0xbd, 0x40, 0xba, 0xe0, 0x4d, 0xa9, 0x9c, 0x71, 0xaa, 0x44,
	0x8d, 0xaa, 0x9e, 0x80, 0x8c, 0x01, 0xcb, 0xa6, 0x0d, 0xfc, 0x18, 0xd4, 0xad, 0x94, 0x6f, 0x9b,
	0xad, 0x74, 0x32, 0x02, 0x6f, 0xb2, 0xa2, 0x89, 0xdc, 0x42, 0xff, 0xb4, 0x69, 0x0c, 0x58, 0xde,
	0xb4, 0x63, 0xd4, 0x04, 0xbc, 0x79, 0x9e, 0x56, 0xa2, 0xaa, 0x73, 0x34, 0x10, 0xfb, 0xeb, 0xe8,
	0x32, 0x64, 0xc7, 0xe8, 0x2e, 0x78, 0xa7, 0x74, 0x49, 0xbf, 0x8d, 0x26, 0x7b, 0x80, 0x65, 0x93,
	0x46, 0x0f, 0x5f, 0x1a, 0xd0, 0x2a, 0x84, 0x2b, 0xfd, 0xa9, 0xe0, 0x19, 0x38, 0xe7, 0x4c, 0x48,
	0xdc, 0xd7, 0x21, 0x95, 0x82, 0x83, 0x83, 0xaa, 0xac, 0x31, 0xa4, 0xf3, 0xf4, 0xfa, 0xf6, 0x6c,
	0xff, 0x42, 0x37, 0x52, 0x95, 0xe2, 0x05, 0x38, 0x31, 0x4d, 0x52, 0x3c, 0xfc, 0xf0, 0x6f, 0xd7,
	0x1b, 0xf8, 0xf5, 0x85, 0x0d, 0x0a, 0x15, 0xea, 0x0f, 0x82, 0x42, 0x45, 0x0f, 0x2c, 0x7d, 0xc4,
	0x4b, 0x70, 0x75, 0x23, 0x06, 0x58, 0x2b, 0xd5, 0x00, 0xeb, 0xc5, 0x91, 0xff, 0x0a, 0xd8, 0x26,
	0x4d, 0x05, 0x3c, 0x51, 0x23, 0xc3, 0x39, 0xb8, 0x7a, 0xd0, 0x86, 0x58, 0xeb, 0xce, 0x10, 0xeb,
	0x7d, 0x10, 0x5f, 0x11, 0x31, 0x28, 0x1d, 0x71, 0x83, 0x9d, 0x81, 0xab, 0x87, 0x6c, 0xb0, 0xb5,
	0x5e, 0x0c, 0xb6, 0xde, 0x85, 0xb9, 0x79, 0xbf, 0x84, 0xbd, 0x76, 0xd5, 0x7f, 0x39, 0x7a, 0x0f,
	0x00, 0x00, 0xff, 0xff, 0x57, 0xb2, 0xdf, 0xf7, 0xcc, 0x03, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// UnitServiceClient is the client API for UnitService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type UnitServiceClient interface {
	List(ctx context.Context, in *GetUnitsRequest, opts ...grpc.CallOption) (*GetUnitsResponse, error)
	Read(ctx context.Context, in *GetOneUnitRequest, opts ...grpc.CallOption) (*GetOneUnitResponse, error)
	Create(ctx context.Context, in *CreateUnitRequest, opts ...grpc.CallOption) (*CreateUnitResponse, error)
	Update(ctx context.Context, in *UpdateUnitRequest, opts ...grpc.CallOption) (*UpdateUnitResponse, error)
	Delete(ctx context.Context, in *DeleteUnitRequest, opts ...grpc.CallOption) (*DeleteUnitResponse, error)
}

type unitServiceClient struct {
	cc *grpc.ClientConn
}

func NewUnitServiceClient(cc *grpc.ClientConn) UnitServiceClient {
	return &unitServiceClient{cc}
}

func (c *unitServiceClient) List(ctx context.Context, in *GetUnitsRequest, opts ...grpc.CallOption) (*GetUnitsResponse, error) {
	out := new(GetUnitsResponse)
	err := c.cc.Invoke(ctx, "/unit.UnitService/List", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *unitServiceClient) Read(ctx context.Context, in *GetOneUnitRequest, opts ...grpc.CallOption) (*GetOneUnitResponse, error) {
	out := new(GetOneUnitResponse)
	err := c.cc.Invoke(ctx, "/unit.UnitService/Read", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *unitServiceClient) Create(ctx context.Context, in *CreateUnitRequest, opts ...grpc.CallOption) (*CreateUnitResponse, error) {
	out := new(CreateUnitResponse)
	err := c.cc.Invoke(ctx, "/unit.UnitService/Create", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *unitServiceClient) Update(ctx context.Context, in *UpdateUnitRequest, opts ...grpc.CallOption) (*UpdateUnitResponse, error) {
	out := new(UpdateUnitResponse)
	err := c.cc.Invoke(ctx, "/unit.UnitService/Update", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *unitServiceClient) Delete(ctx context.Context, in *DeleteUnitRequest, opts ...grpc.CallOption) (*DeleteUnitResponse, error) {
	out := new(DeleteUnitResponse)
	err := c.cc.Invoke(ctx, "/unit.UnitService/Delete", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// UnitServiceServer is the server API for UnitService service.
type UnitServiceServer interface {
	List(context.Context, *GetUnitsRequest) (*GetUnitsResponse, error)
	Read(context.Context, *GetOneUnitRequest) (*GetOneUnitResponse, error)
	Create(context.Context, *CreateUnitRequest) (*CreateUnitResponse, error)
	Update(context.Context, *UpdateUnitRequest) (*UpdateUnitResponse, error)
	Delete(context.Context, *DeleteUnitRequest) (*DeleteUnitResponse, error)
}

// UnimplementedUnitServiceServer can be embedded to have forward compatible implementations.
type UnimplementedUnitServiceServer struct {
}

func (*UnimplementedUnitServiceServer) List(ctx context.Context, req *GetUnitsRequest) (*GetUnitsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method List not implemented")
}
func (*UnimplementedUnitServiceServer) Read(ctx context.Context, req *GetOneUnitRequest) (*GetOneUnitResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Read not implemented")
}
func (*UnimplementedUnitServiceServer) Create(ctx context.Context, req *CreateUnitRequest) (*CreateUnitResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Create not implemented")
}
func (*UnimplementedUnitServiceServer) Update(ctx context.Context, req *UpdateUnitRequest) (*UpdateUnitResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Update not implemented")
}
func (*UnimplementedUnitServiceServer) Delete(ctx context.Context, req *DeleteUnitRequest) (*DeleteUnitResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Delete not implemented")
}

func RegisterUnitServiceServer(s *grpc.Server, srv UnitServiceServer) {
	s.RegisterService(&_UnitService_serviceDesc, srv)
}

func _UnitService_List_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetUnitsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UnitServiceServer).List(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/unit.UnitService/List",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UnitServiceServer).List(ctx, req.(*GetUnitsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _UnitService_Read_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetOneUnitRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UnitServiceServer).Read(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/unit.UnitService/Read",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UnitServiceServer).Read(ctx, req.(*GetOneUnitRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _UnitService_Create_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateUnitRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UnitServiceServer).Create(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/unit.UnitService/Create",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UnitServiceServer).Create(ctx, req.(*CreateUnitRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _UnitService_Update_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateUnitRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UnitServiceServer).Update(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/unit.UnitService/Update",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UnitServiceServer).Update(ctx, req.(*UpdateUnitRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _UnitService_Delete_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteUnitRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UnitServiceServer).Delete(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/unit.UnitService/Delete",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UnitServiceServer).Delete(ctx, req.(*DeleteUnitRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _UnitService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "unit.UnitService",
	HandlerType: (*UnitServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "List",
			Handler:    _UnitService_List_Handler,
		},
		{
			MethodName: "Read",
			Handler:    _UnitService_Read_Handler,
		},
		{
			MethodName: "Create",
			Handler:    _UnitService_Create_Handler,
		},
		{
			MethodName: "Update",
			Handler:    _UnitService_Update_Handler,
		},
		{
			MethodName: "Delete",
			Handler:    _UnitService_Delete_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "service.proto",
}
